/* TenderFlow keeps all document processing inside the browser. */
const state={tender:null,requirements:[],files:[],matches:{},expiry:{},langReady:false};
const $=s=>document.querySelector(s);
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function showNotice(msg,type='error'){const el=$('#notice');el.textContent=msg;el.className=`notice ${type}`;}
function clearNotice(){$('#notice').className='notice hidden';}
function formatBytes(n){return n<1024*1024?`${Math.round(n/1024)} KB`:`${(n/1024/1024).toFixed(1)} MB`}
function validRequirements(data){if(!data||typeof data!=='object'||!data.tender||!Array.isArray(data.requirements))return false;const tnd=data.tender;const tenderKeys=['tender_id','title','procuring_entity','bidder','submission_deadline'];if(tenderKeys.some(k=>typeof tnd[k]!=='string'||!tnd[k].trim()))return false;if(!/^\d{4}-\d{2}-\d{2}$/.test(tnd.submission_deadline))return false;if(!data.requirements.length)return false;return data.requirements.every(r=>r&&typeof r.id==='string'&&Number.isFinite(Number(r.order))&&typeof r.title_en==='string'&&typeof r.title_bn==='string'&&typeof r.mandatory==='boolean'&&typeof r.has_expiry==='boolean')}
function renderTender(){const tnd=state.tender;$('#tender-empty').classList.add('hidden');const box=$('#tender-details');box.classList.remove('hidden');const cells=[['tenderId',tnd.tender_id],['title',tnd.title],['entity',tnd.procuring_entity],['bidder',tnd.bidder],['deadline',tnd.submission_deadline]];box.innerHTML=cells.map(([k,v])=>`<div class="tender-cell ${k==='title'?'wide':''}"><div class="label">${t(k)}</div><div class="value">${escapeHtml(v)}</div></div>`).join('');$('#upload-panel').classList.remove('hidden');$('#check-panel').classList.remove('hidden');renderAll()}
function statusFor(req){const fileId=state.matches[req.id];if(!fileId)return req.mandatory?{key:'missing',block:true}:{key:'notProvided',block:false};if(req.has_expiry){const date=state.expiry[req.id];const validDate=/^\d{4}-\d{2}-\d{2}$/.test(date||'');if(!validDate)return{key:'expiryNeeded',block:true};if(date<state.tender.submission_deadline)return{key:'expired',block:true}}return{key:'ok',block:false}}
function fileById(id){return state.files.find(f=>f.id===id)}
function duplicateGroupUsedByOtherRequirement(file,reqId){return Object.entries(state.matches).some(([rid,matchedId])=>rid!==reqId&&matchedId&&fileById(matchedId)?.hash===file.hash)}
function renderFiles(){const list=$('#files-list');if(!state.files.length){list.innerHTML=`<div class="empty-state"><div class="empty-icon">+</div><p>${t('noFiles')}</p></div>`;return}const groups={};state.files.forEach(f=>(groups[f.hash]??=[]).push(f));list.innerHTML=state.files.map(f=>{const dup=groups[f.hash].length>1?`<div class="duplicate">${t('duplicateOf')} ${groups[f.hash].filter(x=>x.id!==f.id).map(x=>escapeHtml(x.name)).join(', ')}</div>`:'';return `<div class="file-row"><div class="file-main"><span class="pdf-badge">PDF</span><div><div class="file-name" title="${escapeHtml(f.name)}">${escapeHtml(f.name)}</div><div class="file-meta">${f.pages} ${t('pages')} · ${formatBytes(f.size)}</div>${dup}</div></div><button class="remove-btn" data-remove="${f.id}">${t('remove')}</button></div>`}).join('');list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeFile(b.dataset.remove))}
function renderRequirements(){const list=$('#requirements-list');list.innerHTML=state.requirements.map(req=>{const status=statusFor(req);const fileId=state.matches[req.id]||'';const selected=fileById(fileId);const options=[`<option value="">${t('matchPlaceholder')}</option>`].concat(state.files.map(f=>{const usedBy=Object.entries(state.matches).find(([rid,id])=>id===f.id&&rid!==req.id);const hashUsed=duplicateGroupUsedByOtherRequirement(f,req.id);const disabled=Boolean(usedBy||hashUsed);let reason=usedBy?' · already matched':hashUsed?' · duplicate group used':'';return `<option value="${f.id}" ${f.id===fileId?'selected':''} ${disabled?'disabled':''}>${escapeHtml(f.name)}${reason}</option>`})).join('');const datePart=req.has_expiry&&fileId?`<label class="expiry-label">${t('expiry')} <input class="date-input" type="date" value="${escapeHtml(state.expiry[req.id]||'')}" data-expiry="${req.id}"></label>`:'';return `<div class="requirement-row"><div class="order-no">${req.order}</div><div class="req-title">${escapeHtml(currentLang==='bn'?req.title_bn:req.title_en)}<small>${escapeHtml(req.title_en)} · ${req.mandatory?'Required':'Optional'}</small></div><div class="match-wrap"><select class="match-select" data-match="${req.id}">${options}</select>${fileId?`<button class="unmatch-btn" data-unmatch="${req.id}">${t('unmatch')}</button>`:''}${datePart}</div><div class="status-area"><span class="status-badge ${status.block?'block':status.key==='ok'?'ok':'notprovided'}">${t(status.key)}</span></div></div>`}).join('');list.querySelectorAll('[data-match]').forEach(s=>s.onchange=()=>{const id=s.dataset.match;if(s.value){state.matches[id]=s.value}else{delete state.matches[id];delete state.expiry[id]}renderAll()});list.querySelectorAll('[data-unmatch]').forEach(b=>b.onclick=()=>{delete state.matches[b.dataset.unmatch];delete state.expiry[b.dataset.unmatch];renderAll()});list.querySelectorAll('[data-expiry]').forEach(i=>{const updateExpiry=()=>{state.expiry[i.dataset.expiry]=i.value;renderAll()};i.oninput=updateExpiry;i.onchange=updateExpiry})}
function renderSummary(){const statuses=state.requirements.map(statusFor);const blocks=statuses.filter(s=>s.block).length;const okay=statuses.filter(s=>s.key==='ok').length;const optional=statuses.filter(s=>s.key==='notProvided').length;$('#status-summary').innerHTML=`<span class="summary-chip ${blocks?'block':'good'}">${blocks} ${t('blocking')}</span><span class="summary-chip good">${okay} ${t('ok')}</span><span class="summary-chip neutral">${optional} ${t('notProvided')}</span>`;const reasons=state.requirements.map((r,i)=>({r,s:statuses[i]})).filter(x=>x.s.block).map(x=>`${escapeHtml(currentLang==='bn'?x.r.title_bn:x.r.title_en)}: ${t(x.s.key)}`);$('#blockers').innerHTML=reasons.length?reasons.join('<br>'):`<span style="color:var(--green)">${t('ready')}</span>`;$('#generate-btn').disabled=blocks>0}
function renderAll(){renderFiles();renderRequirements();renderSummary()}
async function sha256(bytes){const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function addFiles(fileList){clearNotice();if(!state.tender){showNotice(t('needRequirements'));return}const incoming=[...fileList];if(state.files.length+incoming.length>30){showNotice(t('tooManyFiles'));return}const existingSize=state.files.reduce((n,f)=>n+f.size,0);if(existingSize+incoming.reduce((n,f)=>n+f.size,0)>50*1024*1024){showNotice(t('tooLarge'));return}for(const file of incoming){try{const bytes=await file.arrayBuffer();const header=new TextDecoder().decode(bytes.slice(0,5));if(!file.name.toLowerCase().endsWith('.pdf')||header!=='%PDF-'){showUploadError(`${file.name}: ${t('notPdf')}`);continue}const doc=await PDFLib.PDFDocument.load(bytes,{ignoreEncryption:false});const hash=await sha256(bytes);state.files.push({id:crypto.randomUUID(),name:file.name,size:file.size,pages:doc.getPageCount(),bytes,doc,hash})}catch(e){showUploadError(`${file.name}: ${t('badPdf')}`)}}renderAll()}
function showUploadError(msg){const el=$('#upload-errors');el.classList.remove('hidden');el.textContent=(el.textContent?el.textContent+'\n':'')+`${t('fileRejected')}: ${msg}`}
function removeFile(id){for(const [rid,fid] of Object.entries(state.matches))if(fid===id){delete state.matches[rid];delete state.expiry[rid]}state.files=state.files.filter(f=>f.id!==id);renderAll()}
function sanitize(s){return String(s??'').replace(/[^\x00-\x7F]/g,'?')}
function drawFooter(page,tenderId,num,total,font){const size=10;const left=sanitize(tenderId);const right=sanitize(`Page ${num}`);const color=PDFLib.rgb(0.08,0.12,0.18);const margin=36;page.drawText(left,{x:margin,y:12,size,font,color});const rightWidth=font.widthOfTextAtSize(right,size);page.drawText(right,{x:page.getWidth()-margin-rightWidth,y:12,size,font,color})}
async function generatePackage(){const btn=$('#generate-btn');btn.disabled=true;$('#generation-status').className='generation-status';$('#generation-status').textContent=t('working');await new Promise(r=>setTimeout(r,40));try{const out=await PDFLib.PDFDocument.create();const font=await out.embedFont(PDFLib.StandardFonts.Helvetica);const included=state.requirements.filter(r=>state.matches[r.id]).sort((a,b)=>a.order-b.order);const total=1+included.reduce((n,r)=>n+fileById(state.matches[r.id]).pages,0);const cover=out.addPage([612,792+36]);const navy=PDFLib.rgb(0.05,0.16,0.28),teal=PDFLib.rgb(0.05,0.48,0.43);cover.drawRectangle({x:0,y:828-105,width:612,height:105,color:navy});cover.drawText('TENDER DOCUMENT PACKAGE',{x:42,y:780,size:22,font,color:PDFLib.rgb(1,1,1)});cover.drawText(sanitize(state.tender.tender_id),{x:42,y:751,size:12,font,color:PDFLib.rgb(.65,1,.91)});const meta=[['Tender title',state.tender.title],['Procuring entity',state.tender.procuring_entity],['Bidder',state.tender.bidder],['Submission deadline',state.tender.submission_deadline],['Package made',today()]];let y=688;for(const [label,value] of meta){cover.drawText(label.toUpperCase(),{x:42,y,size:8,font,color:teal});cover.drawText(sanitize(value),{x:42,y:y-18,size:12,font,color:navy});y-=52}cover.drawText('INCLUDED DOCUMENTS',{x:350,y:688,size:8,font,color:teal});let listY=668;const fontSize=included.length>12?8:10;included.forEach((r,i)=>{const text=`${i+1}. ${sanitize(r.title_en)}`;cover.drawText(text,{x:350,y:listY,size:fontSize,font,color:navy});listY-=fontSize+8});drawFooter(cover,state.tender.tender_id,1,total,font);let pageNum=2;for(const req of included){const src=fileById(state.matches[req.id]);for(let i=0;i<src.doc.getPageCount();i++){const sourcePage=src.doc.getPage(i);const w=sourcePage.getWidth(),h=sourcePage.getHeight();const page=out.addPage([w,h+36]);const embedded=await out.embedPage(sourcePage);page.drawPage(embedded,{x:0,y:36,width:w,height:h});drawFooter(page,state.tender.tender_id,pageNum,total,font);pageNum++}}const bytes=await out.save();const blob=new Blob([bytes],{type:'application/pdf'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${state.tender.tender_id}_Package.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);$('#generation-status').textContent=t('success');}catch(e){console.error(e);$('#generation-status').textContent=`${t('loadError')} ${e.message||''}`;btn.disabled=false}}
async function loadRequirements(file){try{const data=JSON.parse(await file.text());if(!validRequirements(data)){showNotice(t('invalidRequirements'));return}state.tender=data.tender;state.requirements=data.requirements.slice().sort((a,b)=>Number(a.order)-Number(b.order));state.matches={};state.expiry={};state.files=[];$('#upload-errors').classList.add('hidden');$('#upload-errors').textContent='';renderTender();clearNotice()}catch(e){showNotice(t('invalidRequirements'))}}
$('#requirements-input').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(state.tender&&!confirm(t('loadReset'))){e.target.value='';return}await loadRequirements(file);e.target.value=''};
$('#pdf-input').onchange=e=>addFiles(e.target.files);const dz=$('#dropzone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('dragover')}));dz.addEventListener('drop',e=>addFiles(e.dataTransfer.files));$('#generate-btn').onclick=generatePackage;document.querySelectorAll('.lang-btn').forEach(b=>b.onclick=()=>setLanguage(b.dataset.lang));$('#theme-toggle').onclick=()=>applyTheme(currentTheme==='dark'?'light':'dark');window.addEventListener('languagechange',()=>{if(state.tender)renderAll()});applyTheme(currentTheme);setLanguage(currentLang);
